from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import DrillingMachineViewSet, ExcavatorViewSet, LoaderViewSet, TransportTruckViewSet, CartView, AddToCartView, RemoveFromCartView, UpdateCartItemView

# Initialize the DefaultRouter
router = DefaultRouter()

# Register your viewsets with appropriate URL routes
router.register(r'drilling-machines', DrillingMachineViewSet)
router.register(r'excavators', ExcavatorViewSet)
router.register(r'loaders', LoaderViewSet)
router.register(r'transport-trucks', TransportTruckViewSet)

# Define URL patterns
urlpatterns = [
    # Include all the routes generated by the DefaultRouter for the machine viewsets
    path('', include(router.urls)),

    # Add custom path for adding to the cart
    path('cart/add/', AddToCartView.as_view(), name='add-to-cart'),  # Add item to cart
    path('cart/', CartView.as_view(), name='cart'),  # Get the user's cart
    path('cart/add/', AddToCartView.as_view(), name='add-to-cart'),  # Add item to cart
    path('cart/remove/', RemoveFromCartView.as_view(), name='remove-from-cart'),  # Remove item from cart
    path('cart/update/', UpdateCartItemView.as_view(), name='update-cart-item'),
]
