# Generated by Django 4.2 on 2025-04-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_course_duration_days_course_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
